- .github/workflows/deploy.yml
- coloraide/__meta__.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/colors/index.md
- docs/src/markdown/index.md
- tests/test_version.py
- Fix version handling of major starting with zero
- Update deployment
- Update docs
> Prepare alpha release

- coloraide/__init__.py
- coloraide/color/__init__.py
- coloraide/color/interpolate.py
- docs/src/dictionary/en-custom.txt
- docs/src/markdown/_snippets/pycode.txt
- docs/src/markdown/api/index.md
- docs/src/markdown/interpolation.md
- tests/test_api.py
- tests/test_roundtrip.py
- tests/test_stops.py
- tools/colors.py
Better handling of linear interpolation
- Allow specifying a channel(s) to interpolate with an easing function
- Allow setting stops and controlling interpolation regions piecewise
> Piecewise lerp

- coloraide/spaces/__init__.py
- docs/src/markdown/about/changelog.md
- tests/test_api.py
- tests/test_hsl.py
- tests/test_hsv.py
- tests/test_hwb.py
- tests/test_lab.py
- tests/test_lch.py
> color() should require % for percent channels

- coloraide/__meta__.py
- coloraide/color/gamut/__init__.py
- coloraide/color/gamut/clip.py
- coloraide/color/gamut/lch_chroma.py
- coloraide/color/interpolate.py
- docs/src/markdown/_snippets/pycode.txt
- docs/src/markdown/about/changelog.md
- tests/test_a98_rgb.py
- tests/test_api.py
- tests/test_display_p3.py
- tests/test_hsl.py
- tests/test_hwb.py
- tests/test_rec2020.py
- tests/test_srgb.py
- tests/test_srgb_linear.py
- tools/colors.py
> Fix gamut mapping algorithm

- docs/src/markdown/_snippets/package.txt
- docs/src/markdown/_snippets/playground.py.txt
- docs/src/markdown/_snippets/playground.txt
- docs/src/markdown/api/index.md
- docs/src/markdown/cat.md
- docs/src/markdown/color.md
- docs/src/markdown/colors/index.md
- docs/src/markdown/compositing.md
- docs/src/markdown/contrast.md
- docs/src/markdown/distance.md
- docs/src/markdown/gamut.md
- docs/src/markdown/index.md
- docs/src/markdown/interpolation.md
- docs/src/markdown/manipulation.md
- docs/src/markdown/playground.md
- docs/src/markdown/strings.md
- docs/theme/colorswatch.css
- mkdocs.yml
- tools/playground.py
- tools/playground.sh
> Make playground work site wide

- coloraide/color/convert/__init__.py
- docs/src/markdown/about/changelog.md
> Ensure NaNs are converted prior to conversion to another space

- docs/src/dictionary/en-custom.txt
- docs/src/markdown/.snippets/playground.md
- docs/src/markdown/.snippets/playground.txt
- docs/src/markdown/playground.md
- docs/theme/playground.css
- mkdocs.yml
- tools/playground.sh
- tools/playground_pyodide.py
- tox.ini
- Allow loading notebook pages
- Add spinner to show pyodide is loading and/or working
> Even better upgrades to playground

- coloraide/gamut/fit_lch_chroma.py
- coloraide/gamut/fit_oklch_chroma.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/colors/index.md
- docs/src/markdown/gamut.md
- tests/test_a98_rgb.py
- tests/test_api.py
- tests/test_display_p3.py
- tests/test_hsl.py
- tests/test_hsv.py
- tests/test_hwb.py
- tests/test_okhsl.py
- tests/test_okhsv.py
- tests/test_prophoto_rgb.py
- tests/test_rec2020.py
- tests/test_srgb.py
- tests/test_srgb_linear.py
> Adjust gamut mapping algorithm to more closely match CSS level 4

- coloraide/color.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/colors/index.md
- tests/test_oklab.py
> Enable CSS oklab and oklch functions

- coloraide/util.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/interpolation.md
- tests/test_api.py
> Interpolate using Oklab as the default instead of CIE LAB

- coloraide/color.py
- coloraide/gamut/__init__.py
- coloraide/gamut/fit_oklch_chroma.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/gamut.md
- docs/src/markdown/plugins/index.md
- tests/test_api.py
- tests/test_display_p3.py
- tests/test_hsl.py
- tests/test_hsv.py
- tests/test_hwb.py
- tests/test_okhsl.py
- tests/test_okhsv.py
- tests/test_prophoto_rgb.py
- tests/test_rec2020.py
- tests/test_srgb.py
- tests/test_srgb_linear.py
> Revert to our old style gamut mapping which has been optimized

- coloraide/interpolate.py
- coloraide/spaces/__init__.py
- coloraide/spaces/srgb/__init__.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/plugins/index.md
> Don't fit spaces when interpolating unless they cannot be represented

- coloraide/color.py
- coloraide/interpolate.py
- coloraide/spaces/__init__.py
- coloraide/spaces/hsl/__init__.py
- coloraide/spaces/hsl/css.py
- coloraide/spaces/hwb/css.py
- coloraide/spaces/lab/css.py
- coloraide/spaces/lch/css.py
- coloraide/spaces/okhsl.py
- coloraide/spaces/oklab/css.py
- coloraide/spaces/oklch/css.py
- coloraide/spaces/srgb/css.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/color.md
- docs/src/markdown/interpolation.md
- docs/src/markdown/manipulation.md
- docs/src/markdown/plugins/index.md
- tests/test_api.py
- tests/test_din99o_lch.py
- tests/test_hsl.py
- tests/test_hsv.py
- tests/test_hwb.py
- tests/test_jzCzhz.py
- tests/test_lch.py
- tests/test_lchuv.py
- tests/test_lchuv_d65.py
- tests/test_okhsl.py
- tests/test_okhsv.py
- tests/test_oklch.py
> Do not assume user defined, powerless hues as undefined

- coloraide/color.py
- coloraide/compositing/__init__.py
- coloraide/compositing/blend_modes.py
- coloraide/compositing/porter_duff.py
- coloraide/distance/__init__.py
- coloraide/gamut/__init__.py
- coloraide/spaces/jzazbz.py
- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- General refactoring in compositing. Classify blend methods (could be
used as plugins in the future).
- Ensure most plugin inputs are consistently case sensitive, the one
exception is color space name which is relaxed to insensitive as the
CSS identifiers themselves are case insensitive and are based off the
plugin name.
> Refactoring

- coloraide/color.py
- coloraide/spaces/__init__.py
- coloraide/spaces/hsl/__init__.py
- coloraide/spaces/hsluv.py
- coloraide/spaces/hsv.py
- coloraide/spaces/hwb/__init__.py
- coloraide/spaces/jzczhz.py
- coloraide/spaces/lch/__init__.py
- coloraide/spaces/okhsl.py
- coloraide/spaces/okhsv.py
- coloraide/spaces/oklch/__init__.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/plugins/index.md
Inputs will now accept and return a single list of coordinates instead
of two inputs/outputs of color coordinates and alpha coordinates.
> Refactor Space.null_adjust to Space.normalize and adjust inputs

- coloraide/color.py
- coloraide/css/serialize.py
- coloraide/interpolate.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/api/index.md
- docs/src/markdown/gamut.md
- docs/src/py/notebook.py
- tests/test_api.py
- tests/test_gamut.py
- tools/compose_imgs.py
- tools/filter_img.py
- tools/gamut_diagram.py
- tools/harmony_diagram.py
`in_place` parameter has been removed from both operations.
Resolves #173
> Gamut mapping/clipping is now done in place by default

- coloraide/color.py
- coloraide/contrast/__init__.py
- coloraide/contrast/wcag21.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/color.md
- docs/src/markdown/contrast.md
- docs/src/markdown/distance.md
- docs/src/markdown/plugins/index.md
- tests/test_api.py
- tests/test_contrast.py
- tests/test_plugin.py
> Expose contrast as a plugin

- coloraide/color.py
- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- docs/src/markdown/about/releases/1.0.md
- docs/src/markdown/color.md
- tests/test_api.py
> Remove naive space filtering

- docs/src/markdown/api/index.md
Still mentions old Bezier approach and is missing B-spline, natural,
monotone and Catmull-Rom.
> Fix interpolation description in docs

- coloraide/algebra.py
Doing some measurements, both of these changes help to improve
calculation speeds to various degrees.
> Some speedups

- coloraide/compositing/__init__.py
- docs/src/markdown/about/changelog.md
- tests/test_blend_modes.py
- tools/compose_imgs.py
> Fix premultiplication handling in compose

- coloraide/color.py
- coloraide/compositing/blend_modes.py
- coloraide/compositing/porter_duff.py
- coloraide/contrast/__init__.py
- coloraide/filters/__init__.py
- coloraide/gamut/fit_lch_chroma.py
- coloraide/interpolate/__init__.py
- tests/test_jzCzhz.py
- Optimize the clip path to be faster. No need to check if in gamut and then clip, when clipping in gamut color, it will remain untouched already.
- More efficient logic for fit that cuts out unnecessary instructions when not needed and improves readability
- Remove various try/catch overhead that can be easily handled in more straight forward ways.
> Changes for better efficiency

- .github/workflows/build.yml
- coloraide/algebra.py
- coloraide/css/parse.py
- coloraide/gamut/__init__.py
- coloraide/harmonies.py
- docs/src/markdown/about/changelog.md
- docs/src/mkdocs.yml
- mkdocs.yml
- tox.ini
Accidentally had part of our regex duplicated. Only failed when hue was a single digit value.
Fixes #257
> Fix OkLCh parsing

- coloraide/algebra.py
- coloraide/cat.py
- coloraide/color.py
- coloraide/css/serialize.py
- coloraide/harmonies.py
- coloraide/interpolate/__init__.py
- coloraide/spaces/cam16.py
- coloraide/spaces/hct.py
- coloraide/spaces/ictcp.py
- coloraide/spaces/orgb.py
> Easy cast removals

- coloraide/color.py
- coloraide/interpolate/bspline.py
- coloraide/interpolate/continuous.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/interpolation.md
- tests/test_interpolation.py
> Add continuous interpolation method

- coloraide/algebra.py
> Improve speed by removing cast() calls

- coloraide/average.py
- Do premultiplication while summing channels
- Undo premultiplication while calculating the mean
- Don't use enumerate in critical loop
> Speed up averaging

- coloraide/color.py
- coloraide/interpolate/__init__.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/api/index.md
- docs/src/markdown/color.md
- docs/src/markdown/interpolation.md
- tests/test_interpolation.py
> Add/expose CSS powerless and carryforward behavior

- coloraide/spaces/hct.py
- docs/src/markdown/about/changelog.md
- tests/test_hct.py
- tests/test_roundtrip.py
Simplify algorithm to favor in visible spectrum colors for speed
> Increase precision for better round trip

- coloraide/__meta__.py
- coloraide/average.py
- coloraide/color.py
- coloraide/distance/__init__.py
- coloraide/interpolate/__init__.py
- coloraide/spaces/__init__.py
- coloraide/spaces/hpluv.py
- coloraide/spaces/jzczhz.py
- coloraide/spaces/zcam_jmh.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/api/index.md
- docs/src/markdown/demos/3d_models.html
- docs/src/markdown/demos/colorpicker.html
- docs/src/markdown/distance.md
- docs/src/markdown/manipulation.md
- docs/src/markdown/plugins/space.md
- docs/src/mkdocs.yml
- docs/theme/playground-config-3905dc29.js
- docs/theme/playground-config-6f907977.js
- mkdocs.yml
- tests/test_api.py
- tests/test_distance.py
- tests/test_hsl.py
- tests/test_hsluv/test_hpluv.py
- tests/test_hsv.py
- tests/test_hwb.py
- tests/test_jzczhz.py
- tests/test_lch.py
- tests/test_zcam_jmh.py
- tools/gamut_3d_plotly.py
- Add is_polar method
- Add methods to color space objects to quickly access radial coordinate
- Allow euclidean distance to handle polar spaces
> Polar handling

- coloraide/gamut/fit_raytrace.py
- coloraide/spaces/hsl/__init__.py
- coloraide/spaces/hsv.py
- coloraide/spaces/hwb/__init__.py
- docs/src/markdown/about/changelog.md
- docs/src/markdown/colors/index.md
- tests/test_hsv.py
This removes HSV and HWB reliance on HSL.
> refactor out the reliance of HWB and HSV on HSL

- coloraide/color.py
- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
> Add Jupyter HTML output representation

- coloraide/algebra.py
- coloraide/easing.py
- docs/src/dictionary/en-custom.txt
- docs/src/markdown/about/changelog.md
- tests/test_algebra.py
- tests/test_easing.py
There is no need to solve a quadratic or cubic polynomial with Newton's method. There are algebraic solutions that are faster and more reliable. Add functions to solve cubic, quadratic, and linear functions. Functions will filter out imaginary solutions.
> Better polynomial solving up to cubic

- coloraide/algebra.py
- coloraide/gamut/fit_minde_chroma.py
- coloraide/spaces/hsl/__init__.py
- coloraide/spaces/hsv.py
- coloraide/spaces/lab/__init__.py
- coloraide/spaces/lch/__init__.py
- docs/src/markdown/about/changelog.md
- Improve accuracy of "order"
- Ensure we are handling negative "order" properly in achromatic checks
> Order of magnitude fixes

- docs/src/markdown/distance.md
By the way, thank you for this project. It has been exactly what I've been looking for for a while now!
> teeny typo
