coloraide/colors/_gamut.py
coloraide/colors/_parse.py
coloraide/colors/_range.py
coloraide/colors/_rgb.py
coloraide/colors/_space.py
coloraide/colors/hsl.py
coloraide/colors/hsv.py
coloraide/colors/hwb.py
coloraide/colors/lab.py
coloraide/colors/lch.py
coloraide/colors/xyz.py

This is intended to close #5.
Unfortunately, there is some uncertainty about the implementation. Currently, like colorjs, we blindly just treat percentages as a representation of values in the range 0 - 1, even if the color space we are referring to does not store their values as such. The spec is unclear of how this should be handled, and I'm not yet convinced that colorjs is doing it as intended, but maybe they are. Really, it all comes down to what the spec intends, which is currently ambiguous.
This is a work in progress as we need to understand what the true intention is.
@gir-bot add S: work-in-progress

Handle percents in non-alpha channels using the color function

---

coloraide/colors/_space.py
coloraide/colors/srgb.py
docs/src/markdown/index.md
mkdocs.yml

Recent change in the CSS specification now requires color to specify
the space if not using the form `color(<digit>+)`. So no more assumed
srgb space.

Require the color space in color() function

---

coloraide/__meta__.py
coloraide/colors/__init__.py
coloraide/colors/_convert.py
coloraide/colors/_rgb.py
coloraide/colors/a98_rgb.py
coloraide/colors/display_p3.py
coloraide/colors/hsl.py
coloraide/colors/hsv.py
coloraide/colors/hwb.py
coloraide/colors/lab.py
coloraide/colors/lch.py
coloraide/colors/prophoto_rgb.py
coloraide/colors/rec2020.py
coloraide/colors/srgb.py
coloraide/colors/xyz.py
requirements/docs.txt
tests/test_roundtrip.py

Make conversion logic more manageable by reusing a lot of the code using
common way-points for conversion:
- Some color spaces may have shortcuts to other related color spaces,
those should be considered first.
- If there are no shortcuts, spaces should be converted by passing
through the XYZ space.
Implementing this logic greatly reduces the number of functions we have
to have and makes it easier to maintain.
Also, make sure all the convert functions take a list of channels
opposed to some taking individual channels.
Fixes #1

Clean up conversion logic

---

coloraide/colors/lch.py
coloraide/css/colors/lab.py
docs/src/markdown/gamut.md
docs/src/markdown/interpolation.md

The workaround in colorjs.io that forces hue to zero during conversion
of lab to lch actually can throw off some conversions to a small degree.
They do this by setting the hue to NaN, which is treated as zero in
color space conversion. I believe the intention of this is mainly for
color interpolation. We calculate whether we should consider the hue
during interpolation at time of interpolation, so we don't need this
logic.

Don't force hue to zero in translation of lab to lch

---

coloraide/colors/_convert.py
coloraide/colors/_cylindrical.py
coloraide/colors/_parse.py
coloraide/colors/hsl.py
coloraide/colors/hsv.py
coloraide/colors/hwb.py
coloraide/colors/lch.py
docs/src/markdown/interpolation.md
docs/theme/colorswatch.css
mkdocs.yml
tools/colors.py

We were always constraining hue to be between 0-360, so it was
impossible for us to properly implement hue "specified" logic.
Fix hue so that it is only constrained when an actual conversion
between spaces occurs.
Also, add gradient boxes to docs and visualize hue logic.

Fix hue-specified not working

---

coloraide/colors/_gamut.py
coloraide/colors/_space.py
coloraide/colors/hsl.py
coloraide/colors/hsv.py
coloraide/colors/hwb.py

1. HSL, HSV, and HWB should use sRGB to determine if they are in gamut
as they are just cylindrical representations of sRGB.
2. While point (1) is true, there are cases, due to conversion
algorithms, where an sRGB color may be slightly out of gamut (and
within the allowable threshold) and appear in gamut, but the
cylindrical representation is grossly out of spec. In this case, we
should at least make sure the cylindrical representation is within an
allowable threshold as well.
3. When fitting, fitting the parent gamut (in the case of HSL, the
parent being sRGB) if the parent is fit, the child should fit as no
threshold is used when fitting.
4. When passing anything through fit, we will always normalize angles to
be between 0-360 for consistency.

Better gamut handling

---

coloraide/__meta__.py
coloraide/colors/hsv.py
coloraide/colors/hwb.py
docs/src/markdown/about/changelog.md

1. Ensure HSV always sets NaN when needed as there were times it did not
2. Instead of sending HWB conversions through sRGB, send conversions
through HSV which gives cleaner results.

Make some adjustments to conversions for HWB and HSV

---

coloraide/color/gamut/lch_chroma.py

As shown in both the code and the original implementation of this gamut mapping algorithm in Color.js, it reduces chroma, not lightness.

Fix typo in gamut mapping docs

---

docs/src/markdown/.snippets/playground.md
docs/src/markdown/.snippets/playground.txt
docs/theme/playground.css
tools/playground.py

Playground code blocks improve performance and usability.
- Do not syntax highlight code while editing. While cool, and useful,
it is slow on mobile devices and very under-powered devices,
especially when dealing with large code size. Don't syntax highlight
so that that editing loads faster and is not bogged down with Pygments
processing which is not designed to be used for live editing.
- Show traces when a command fails. This is useful to the user so they
know they did something wrong, and what.
Overall, the experience should be better, even if we lose live syntax
highlighting.

Better playground experience

---

coloraide/spaces/hwb/css.py
coloraide/spaces/lab/css.py
coloraide/spaces/lch/css.py
coloraide/spaces/oklab/css.py
coloraide/spaces/oklch/css.py
docs/src/markdown/about/changelog.md
docs/src/markdown/strings.md
tests/test_hwb.py
tests/test_lab.py
tests/test_lch.py
tests/test_oklab.py
tests/test_oklch.py

HWB, Lch, Lab, Oklch, and Oklab will no longer allow commas in their
format. They are not officially part of the CSS spec.
It is clear now that CSS will not allow commas in the new formats. The idea surfaced and was rejected. If we are claiming to parse CSS formats, we should parse them as they are specified.

Ensure that we are more strictly following CSS format for commas

---

coloraide/interpolate.py
docs/src/markdown/about/changelog.md

Ensure `longer` evaluates longer when ∆θ = 0

---

coloraide/color.py
coloraide/convert.py
coloraide/cvd.py

Once the optimal conversion chain is calculated for a color class,
cache it to speed up future conversions between the two color spaces.
When registering or deregistering color space plugins, clear the cache.
If subclassing, ensure the new class does not use the parent class's
cache.

Cache the conversion chain to speed up conversions more

---

tests/test_api.py

We were getting lucky with a quirk of Python. If you refer to the same
instance of NaN within a sequence, Python will compare and return True.
It should not though.
Rework test so that this doesn't fail in case Python fixes this issue.

Nan test fix

---

coloraide/__meta__.py
coloraide/color.py
coloraide/interpolate/__init__.py
coloraide/interpolate/bspline.py
coloraide/interpolate/linear.py
docs/src/dictionary/en-custom.txt
docs/src/markdown/about/changelog.md
docs/src/markdown/api/index.md
docs/src/markdown/plugins/interpolate.md
docs/src/mkdocs.yml
docs/theme/playground-config-1e20e984.js
docs/theme/playground-config-3c7321de.js
mkdocs.yml
tests/test_interpolation.py
tools/interp_diagram.py

We do not currently do extrapolation in any of our interpolators, but
we shouldn't make it difficult to do so.
The desired point on the interpolation line should remain unmodified
through the call chain up until the a user would write custom
interpolation code, e.g. the `interpolate` function of the
`Interpolator` class.
Once there, they can decide if they'd like to not clamp the value. This
can be useful if a periodic, closed loop interpolator was desired. In
this case, it may be beneficial to allow values beyond 0 and 1, and wrap
them.
Resolves #230 
Resolves #229

Slight refactor to base interpolate plugin in regards to extrapolation

---

coloraide/spaces/rec2100_hlg.py

Set lb to 0 and lw to 1000 as these are the minimums for each range. Gamma will calculate to about 1.2, but it'll make no difference as the black level lift will be calculated as zero for us anyways due to lb = 0
If we end up changing lb at some point, gamma will have an actual impact

Add proper handling of gamma and black level lift

---

coloraide/spaces/hct.py
docs/src/markdown/colors/hct.md
tests/test_hct.py

We curve fitted CAM16 J vs HCT T to come up with a polynomial to guess the best J possible for Newton Raphson. If the color has a very wide gamut, we will just correct the luminance in XYZ instead as the J vs T relationship changes as chroma gets larger causing the initial J guess to get worse in some regions as chroma increase.

Even faster HCT conversion

---

coloraide/temperature/ohno_2013.py
coloraide/temperature/planck.py
coloraide/temperature/robertson_1968.py
tests/test_cct.py

We should use the recommended C2 constant for CCT as recommended in ITS-90. The difference is simply that the constant is rounded to 6 places and affects values slightly.

Use ITS-90 C2 and C1 constant for CCT

---

coloraide/algebra.py
docs/src/py/notebook.py
pyproject.toml
tests/test_algebra.py

We should now be able to sort the rows such that the diagonal never have zeros in them unless the matrix is invertible. We seem to be able to handle 30 x 30 2D matrices, much larger than we would ever need. There are certainly cases that could stress this, but from the perspective of what we need for colors, this should be good enough.

Fix inv row sorting once and for all

---

coloraide/algebra.py
tests/test_algebra.py

`inv` is now much closer to prior speeds with the addition of being more reliable and `solve` is also faster. `solve(m, v)` is still faster than `dot(inv(m), v)`. Though probably not needed, `lu` can handle tall and wide matrices. `det`, which is based off of `lu` is faster as well. `trace` added in case we need it, used by `det`.

Speed ups to LU related methods, much closer to previous speeds

---

coloraide/distance/delta_e_2000.py
coloraide/distance/delta_e_76.py
coloraide/distance/delta_e_94.py
coloraide/distance/delta_e_99o.py
coloraide/distance/delta_e_cmc.py
coloraide/distance/delta_e_ok.py
coloraide/gamut/fit_hct_chroma.py
coloraide/gamut/fit_lch_chroma.py
coloraide/gamut/fit_oklch_chroma.py
coloraide/spaces/lab/__init__.py
coloraide/spaces/lab/css.py
coloraide/spaces/lab_d65.py
coloraide/spaces/lch/__init__.py
coloraide/spaces/lch/css.py
coloraide/spaces/lch_d65.py
docs/src/markdown/about/changelog.md
docs/src/markdown/distance.md
tests/test_distance.py

CIE Lab based delta E algorithms should allow specifying a specific CIE Lab variant (D50 vs D65, etc.)
We imply based on our references that all the CIE Lab algorithms are based on Lab D65, but CMC and 94 were using D50. Fix this inconsistency. If people want D50, we've now exposed ways to do this on demand or by setting it as the default.
Resolve #361

Fix some delta-e issues and expose config options

---

coloraide/algebra.py
coloraide/types.py
docs/src/markdown/about/changelog.md

This is a better typing for tensor. It will, unfortunately, still be difficult for mypy to know how deep the tensor is, requiring us to type the variables they are unpacked into, but they now won't break typing if actually used.
Fixes #375

A Tensor type that actually works

---

coloraide/color.py
coloraide/interpolate/__init__.py
coloraide/spaces/__init__.py
tools/interp_diagram.py
tools/slice_diagram.py

Allow negative indexes to work in get/set.
Abandon treating numerical values as aliases. Instead, utilize a mapping of channel name to index.

Better handling of numerical values in get/set

---

coloraide/color.py
coloraide/interpolate/__init__.py
docs/src/markdown/about/changelog.md

Because we were "discretizing" interpolations in place, spline-based interpolators were still affecting the edges of discrete blocks as these interpolators take into account more than two colors. After generating the discrete steps, package it up into a linear interpolator and return that.

Ensure spline based interpolation is truly discrete when using discrete

---

coloraide/gamut/fit_raytrace.py
coloraide/interpolate/__init__.py
docs/src/markdown/about/changelog.md
tests/test_gamut.py
tests/test_interpolation.py

Also, provide more helpful error when an empty list is used.

Gracefully handle interpolation of a single color

---

coloraide/distance/delta_e_cam16.py
docs/src/markdown/about/changelog.md
docs/src/markdown/distance.md
tests/test_distance.py

- ∆Ecam16 can now have the UCS space specified via "space". This can be any space derived from CAM16UCS.

Make using different CAM16 UCS spaces for ∆Ecam16 possible

---

coloraide/algebra.py
coloraide/interpolate/__init__.py
coloraide/spaces/a98_rgb.py
coloraide/spaces/cam16_jmh.py
coloraide/spaces/hct.py
coloraide/spaces/hpluv.py
coloraide/spaces/hsluv.py
coloraide/spaces/hunter_lab.py
coloraide/spaces/ictcp.py
coloraide/spaces/igpgtg.py
coloraide/spaces/ipt.py
coloraide/spaces/jzazbz.py
coloraide/spaces/jzczhz.py
coloraide/spaces/prophoto_rgb.py
coloraide/spaces/rec2100_pq.py
coloraide/spaces/rlab.py
coloraide/util.py
docs/src/dictionary/en-custom.txt
docs/src/markdown/about/changelog.md
docs/src/markdown/colors/cam16_jmh.md
docs/src/markdown/colors/rlab.md
docs/src/markdown/gamut.md
tests/test_algebra.py
tests/test_gamut.py

- Add utility functions to do common scaling from 1 to 100 and 100 to 1
- Absolute value XYZ conversion won't force clamping of negative values.
- Ensure ST2084 EOTF implements the max step as specified in the spec.
- Rework environment objects to accept white points as chromaticity points as it was done previously.

Some cleanup and fixes

---

docs/src/markdown/color.md

I believe this section is explaining that `update` is updating the color, but not changing the color space, in contrast to mutate which will update both color and color space.

docs: Fix wording in the description of the color update method

---

coloraide/color.py
docs/src/markdown/about/changelog.md
docs/src/markdown/api/index.md
docs/src/markdown/compositing.md
tests/test_compositing.py
tools/compose_imgs.py

Add layer() which has a more intuitive name than compose() and aligns with multi-color handling similar to other API methods that handle multi-color, like interpolate(), average(), steps(), etc.

Add layer() and deprecate compose()

---

coloraide/gamut/fit_raytrace.py
docs/src/markdown/gamut.md
tests/test_gamut.py
tools/raytrace_test.py

When using ray trace and the adaptive lightness approach, Luv and its cylindrical counter part can produce chroma reduction curves that stress the algorithm in the dark blue region. This can yield yellows which make no sense.
Add a restriction in the correction code that projects the color onto the chroma reduction vector in the Lab model to restrict extreme results, outside the range of the vector, which can create colors outside the color space's ability to convert the color causing massive hue shifts.
Colors will still not be accurate, but they will be much closer to then intended target and be a more sane representation.

Restrict correction algorithm to produce sane results in extreme cases

---

.github/workflows/build.yml
.github/workflows/deploy.yml
coloraide/algebra.py
coloraide/types.py
docs/src/markdown/about/changelog.md
hatch_build.py
pyproject.toml
tests/test_algebra.py

- Narrow the shape type to tuples which we can actually have a more fine grained approach with.
- In a few cases we could accept a float shape of an empty tuple, but that was not communicated by certain functions.
Typing is messy and not perfect in algebra lib, but this should help a bit. Ignore cases where things are too dynamic for mypy to figure things out.

Fix shape typing and other related typing issues

---

coloraide/algebra.py
coloraide/types.py

This used to not work with mypy, but now it seems to be working. This is a cleaner, better approach.
Related #375

Use forward referencing for array types
